# Neon.tech Database
spring.datasource.url=jdbc:postgresql://ep-royal-glitter-aqxv1b59-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7TKvHpJNXVD0
spring.datasource.hikari.maximumPoolSize=5

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto
server.port=8080

# Logs
logging.level.com.cloudnative=DEBUG